Repository trungleduc/ipecharts, pull requests merged in 2024-09, with the labels that each got.

#10 feat: add style config
  README.md
  docs/source/images/update_style.mp4
  ipecharts/echarts.py
  src/rawWidget.ts
  src/widget.ts
Labels: enhancement

#12 add dynamic style vide
  README.md
Labels: documentation

#15 Add integration tests
  .eslintignore
  .github/workflows/build.yml
  .github/workflows/update_galata_references.yaml
  .gitignore
  README.md
  docs/source/index.rst
  example/example.ipynb
  generate_code/main.py
  src/plugin.ts
  ui-tests/jupyter_server_test_config.py
  ui-tests/package.json
  ui-tests/playwright.config.js
  ui-tests/tests/ui.spec.ts
  ui-tests/tests/ui.spec.ts-snapshots/Widget-at-cell-1-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/Widget-at-cell-2-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/Widget-at-cell-3-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/Widget-at-cell-4-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/Widget-at-cell-5-linux.png
  ui-tests/yarn.lock
  yarn.lock
Labels: maintenance

#14 Refactor widget classes
  ipecharts/baseechartswidget.py
  ipecharts/echarts.py
  src/baseWidget.ts
  src/plugin.ts
  src/rawWidget.ts
  src/widget.ts
Labels: enhancement
